apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: maubot
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml
