# Swift container initialization for Loki
swift:
  enabled: true
  proxy_url: "http://swift-proxy-preprod-svc.swift-proxy.svc.cluster.local:8000"
  username: <path:secret/data/loki#swift_username>
  password: <path:secret/data/loki#swift_password>
  containers:
    - loki-chunks
    - loki-ruler
