grafana:
  sidecar:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
    dashboards:
      enabled: true
      defaultFolderName: "General"
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana_folder
      searchNamespace: grafana
      provider:
        name: sidecarProvider
        orgId: 1
        type: file
        disableDelete: false
        allowUiUpdates: true
        foldersFromFilesStructure: true
  grafana.ini:
    server:
      root_url: https://grafana.eco-preprod.tsi-dev.otc-service.com
    auth.generic_oauth:
      enabled: true
      name: Zitadel
      allow_sign_up: true
      auto_login: false
      scopes: openid email profile groups urn:zitadel:iam:org:project:roles
      client_id: <path:secret/data/grafana/config#zitadel_client_id>
      client_secret: <path:secret/data/grafana/config#zitadel_client_secret>
      auth_url: https://zitadel.eco-preprod.tsi-dev.otc-service.com/oauth/v2/authorize
      token_url: https://zitadel.eco-preprod.tsi-dev.otc-service.com/oauth/v2/token
      api_url: https://zitadel.eco-preprod.tsi-dev.otc-service.com/oidc/v1/userinfo
      use_pkce: true
      use_refresh_token: true
      signout_redirect_url: https://zitadel.eco-preprod.tsi-dev.otc-service.com/oidc/v1/end_session
      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-editor') && 'Editor' || 'Viewer'
      role_attribute_strict: true
      tls_skip_verify_insecure: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      deleteDatasources:
      - name: Loki
        orgId: 1
      - name: Prometheus
        orgId: 1
      - name: Victoria Metrics
        orgId: 1
      - name: Tempo
        orgId: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: https://loki.eco-preprod.tsi-dev.otc-service.com
        orgId: '1'
        uid: 'loki'
        basicAuth: true
        basicAuthUser: <path:secret/data/loki#gateway_username>
        isDefault: false
        jsonData:
          maxLines: 1000
          tlsSkipVerify: false
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          basicAuthPassword: <path:secret/data/loki#gateway_password>
          httpHeaderValue1: <path:secret/data/grafana/config#loki_orgid>
        version: '1'
        editable: true
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: '1'
        uid: 'prometheus'
        url: http://kube-prometheus-stack-prep-prometheus.monitoring.svc.cluster.local:9090
        isDefault: false
        jsonData:
          tlsSkipVerify: false
        version: '1'
        editable: true
      - name: Victoria Metrics
        type: prometheus
        access: proxy
        orgId: '1'
        uid: 'victoriametrics'
        url: https://vm.eco-preprod.tsi-dev.otc-service.com/prometheus
        isDefault: true
        basicAuth: true
        basicAuthUser: <path:secret/data/victoriametrics/preprod#vmauth_username>
        jsonData:
          tlsSkipVerify: false
        secureJsonData:
          basicAuthPassword: <path:secret/data/victoriametrics/preprod#vmauth_password>
        version: '1'
        editable: true
      - name: Tempo
        type: tempo
        access: proxy
        orgId: '1'
        uid: 'tempo'
        url: http://tempo-preprod.tempo.svc.cluster.local:3200
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: 'loki'
            filterByTraceID: true
            filterBySpanID: true
          tracesToMetrics:
            datasourceUid: 'prometheus'
          nodeGraph:
            enabled: true
          serviceMap:
            datasourceUid: 'prometheus'
        version: '1'
        editable: true

  replicas: 1

  serviceMonitor:
    enabled: true
    path: /metrics
    namespace: monitoring
    labels:
      release: kube-prometheus-stack-preprod
    interval: 30s
    scheme: http
    scrapeTimeout: 30s

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/private-key-algorithm: RSA
      cert-manager.io/private-key-size: "4096"
      cert-manager.io/private-key-rotation-policy: Always
    path: /
    port: http
    pathType: Prefix
    hosts:
      - grafana.eco-preprod.tsi-dev.otc-service.com
    tls:
      - secretName: grafana-ingress-tls
        hosts:
          - grafana.eco-preprod.tsi-dev.otc-service.com

  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi

  deploymentStrategy:
    type: Recreate

  persistence:
    type: pvc
    enabled: true
    storageClassName: csi-disk-retain
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  assertNoLeakedSecrets: false
