apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opensearch_security_config_secret_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opensearch-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: system-config
type: Opaque
stringData:
  internal_users.yml: {{ .Values.internal_users_yml | quote }}
  config.yml: {{ .Values.config_yml | quote }}
  roles.yml: {{ .Values.roles_yml | quote }}
  roles_mapping.yml: {{ .Values.roles_mapping_yml | quote }}
