---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | quote }}
