---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-db-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.db.host | quote }}
  database: {{ .Values.db.database | quote }}
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}
