---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-oauth-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: {{ .Values.oauth.clientId | quote }}
  secret: {{ .Values.oauth.clientSecret | quote }}
