---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-obs-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  access_key: {{ .Values.obs.accessKey | quote }}
  secret_key: {{ .Values.obs.secretKey | quote }}
