---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-security-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ .Values.security.secretKey | quote }}
  internal_token: {{ .Values.security.internalToken | quote }}
