---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-smtp-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.smtp.host | quote }}
  username: {{ .Values.smtp.username | quote }}
  password: {{ .Values.smtp.password | quote }}
