---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-valkey-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea-additional-manifests.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.valkey.password | quote }}
