apiVersion: v1
kind: Secret
metadata:
  name: giji-env
type: Opaque
stringData:
  GITHUB_TOKEN: <path:secret/data/github/otcbot#otcbot_giji_token>
  GITHUB_API_URL: <path:secret/data/helpcenter/monitoring/github#github_api_url>
  GITHUB_ORGS: <path:secret/data/helpcenter/monitoring/github#github_orgs>
  DB_HOST: <path:secret/data/helpcenter/monitoring/postgresql#host>
  DB_PORT: <path:secret/data/helpcenter/monitoring/postgresql#port>
  DB_CSV: <path:secret/data/helpcenter/monitoring/postgresql#dbname>
  DB_USER: <path:secret/data/helpcenter/monitoring/postgresql#username>
  DB_PASSWORD: <path:secret/data/helpcenter/monitoring/postgresql#password>
  BASE_GITEA_URL: <path:secret/data/gitea/config#gitea_address>
  JIRA_API_URL: <path:secret/data/jira/autoecobot#jira_api_url>
  JIRA_TOKEN: <path:secret/data/jira/autoecobot#jira_api_key>
  JIRA_CERT_PATH: /etc/giji/certs/jira-cert.pem
  JIRA_KEY_PATH: /etc/giji/certs/jira-key.pem
  DEH: <path:secret/data/giji/master_component#dedicated-host>
  ASG: <path:secret/data/giji/master_component#auto-scaling>
  ECS: <path:secret/data/giji/master_component#elastic-cloud-server>
  IMS: <path:secret/data/giji/master_component#image-management-service>
  BMS: <path:secret/data/giji/master_component#bare-metal-server>
  RDS: <path:secret/data/giji/master_component#relational-database-service>
  OPENGAUSS: <path:secret/data/giji/master_component#gaussdb-opengauss>
  GEMINIDB: <path:secret/data/giji/master_component#geminidb>
  MYSQL: <path:secret/data/giji/master_component#gaussdb-mysql>
  DRS: <path:secret/data/giji/master_component#data-replication-service>
  DAS: <path:secret/data/giji/master_component#data-admin-service>
  DDM: <path:secret/data/giji/master_component#distributed-database-middleware>
  DDS: <path:secret/data/giji/master_component#document-database-service>
  MKT: <path:secret/data/giji/master_component#marketplace>
  CSS: <path:secret/data/giji/master_component#cloud-search-service>
  DWS: <path:secret/data/giji/master_component#data-warehouse-service>
  MRS: <path:secret/data/giji/master_component#mapreduce-service>
  MA: <path:secret/data/giji/master_component#modelarts>
  CES: <path:secret/data/giji/master_component#cloud-eye>
  CCE: <path:secret/data/giji/master_component#cloud-container-engine>
  CCI: <path:secret/data/giji/master_component#cloud-container-instance>
  ED: <path:secret/data/giji/master_component#enterprise-dashboard>
  SD: <path:secret/data/giji/master_component#status-dashboard>
  DC: <path:secret/data/giji/master_component#direct-connect>
  DNS: <path:secret/data/giji/master_component#domain-name-service>
  ELB: <path:secret/data/giji/master_component#elastic-load-balancing>
  APIG: <path:secret/data/giji/master_component#api-gateway>
  AOM: <path:secret/data/giji/master_component#application-operations-management>
  APM: <path:secret/data/giji/master_component#application-performance-management>
  CTS: <path:secret/data/giji/master_component#cloud-trace-service>
  DCS: <path:secret/data/giji/master_component#distributed-cache-service>
  FGS: <path:secret/data/giji/master_component#function-graph>
  LTS: <path:secret/data/giji/master_component#log-tank-service>
  HSS: <path:secret/data/giji/master_component#host-security-service>
  IAM: <path:secret/data/giji/master_component#identity-access-management>
  KMS: <path:secret/data/giji/master_component#key-management-service>
  DLI: <path:secret/data/giji/master_component#data-lake-insight>
  DAS_STUDIO: <path:secret/data/giji/master_component#data-arts-studio>
  OCR: <path:secret/data/giji/master_component#optical-character-recognition>
  CCN: <path:secret/data/giji/master_component#cloud-connect>
  EIP: <path:secret/data/giji/master_component#elastic-ip>
  ER: <path:secret/data/giji/master_component#enterprise-router>
  ESW: <path:secret/data/giji/master_component#enterprise-switch>
  NATGW: <path:secret/data/giji/master_component#nat-gateway>
  PLAS: <path:secret/data/giji/master_component#private-link-access-service>
  VPC: <path:secret/data/giji/master_component#virtual-private-cloud>
  VPCEP: <path:secret/data/giji/master_component#vpc-endpoint>
  VPN: <path:secret/data/giji/master_component#virtual-private-network>
  ANTIDDOS: <path:secret/data/giji/master_component#anti-ddos>
  CFW: <path:secret/data/giji/master_component#cloud-firewall>
  DBSS: <path:secret/data/giji/master_component#database-security-service>
  EPS: <path:secret/data/giji/master_component#enterprise-project-service>
  WAF: <path:secret/data/giji/master_component#web-application-firewall>
  ASM: <path:secret/data/giji/master_component#application-service-mesh>
  SWR: <path:secret/data/giji/master_component#software-repository-container>
  DMS: <path:secret/data/giji/master_component#distributed-message-service>
  DMSROCKETMQ: <path:secret/data/giji/master_component#distributed-message-service-rocketmq>
  CBR: <path:secret/data/giji/master_component#cloud-backup-recovery>
  CSBS: <path:secret/data/giji/master_component#cloud-server-backup-service>
  EVS: <path:secret/data/giji/master_component#elastic-volume-service>
  OBS: <path:secret/data/giji/master_component#object-storage-service>
  SDRS: <path:secret/data/giji/master_component#storage-disaster-recovery-service>
  SFS: <path:secret/data/giji/master_component#scalable-file-service>
  VBS: <path:secret/data/giji/master_component#volume-backup-service>
  CONFIG: <path:secret/data/giji/master_component#config>
  RFS: <path:secret/data/giji/master_component#resource-formation-service>
  SMN: <path:secret/data/giji/master_component#simple-message-notification>
  TMS: <path:secret/data/giji/master_component#tag-management-service>
  TAURUSDB: <path:secret/data/giji/master_component#taurusdb>
  TARGET_SQUADS: <path:secret/data/giji/config#target_squads>
  IMPORTED_LABEL: <path:secret/data/giji/config#imported_label>
  JIRA_PROJECT_KEY: <path:secret/data/giji/config#jira_project_key>
  JIRA_ISSUE_TYPE: <path:secret/data/giji/config#jira_issue_tag>
  QA: <path:secret/data/giji/config#QA>
  UAT: <path:secret/data/giji/config#UAT>
  SEC: <path:secret/data/giji/config#SEC>
  master_component: <path:secret/data/giji/config#master_component>
  users_impact: <path:secret/data/giji/fields_map#users_impact>
  affected_locations: <path:secret/data/giji/config#affected_locations>
  test_category: <path:secret/data/giji/config#test_category>
  priority: <path:secret/data/giji/config#priority>
  bug_type: <path:secret/data/giji/config#bug_type>
  affected_areas: <path:secret/data/giji/config#affected_areas>
  estimated_effort: <path:secret/data/giji/config#estimated_effort>
  tier: <path:secret/data/giji/config#tier>
  pays_into: <path:secret/data/giji/config#pays_into>
  description: <path:secret/data/giji/config#description>
