apiVersion: v1
kind: Service
metadata:
  name: vllm-service-headless
  labels:
    app: vllm
spec:
  clusterIP: None
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
