clusterIssuers:
  - name: letsencrypt-prod
    email: <path:secret/data/smtp_gw#email_address>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: letsencrypt-prod-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
  - name: letsencrypt-staging
    email: <path:secret/data/smtp_gw#email_address>
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: letsencrypt-stg-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
