apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift-proxy
spec:
  template:
    spec:
      serviceAccountName: "swift-proxy-swiss"
      containers:
        - name: "swift-proxy"
          volumeMounts:
            - mountPath: "/etc/openstack"
              name: "secrets"

      volumes:
        - name: "secrets"
          secret:
            defaultMode: 420
            secretName: "swift-proxy-clouds"
