apiVersion: v1
kind: Service
metadata:
  name: llamacpp-headless
  labels:
    app: llamacpp
spec:
  clusterIP: None
  selector:
    app: llamacpp
  ports:
    - name: http
      port: 8000
      targetPort: 8080
      protocol: TCP