apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamacpp-models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-sfs-llamacpp
  resources:
    requests:
      storage: 50Gi