clusters:
  cluster-192.168.150.27-3666497632:
    name: preprod
    server: "<path:secret/data/argocd/clusters/preprod#server>"
    config:
      tlsClientConfig:
        insecure: false
        caData: "<path:secret/data/argocd/clusters/preprod#caData>"
        certData: "<path:secret/data/argocd/clusters/preprod#certData>"
        keyData: "<path:secret/data/argocd/clusters/preprod#keyData>"
