apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sa.yaml
  - components/valkey

configMapGenerator:
  - name: cap-config
    literals:
      - SERVER_PORT=3000
      - SERVER_HOSTNAME=0.0.0.0
      - REDIS_URL=redis://valkey.valkey.svc.cluster.local:6379
      - DEMO_MODE=false
      - SHOW_ERRORS=false
      - DISABLE_ERROR_LOGGING=false

secretGenerator:
  - name: cap-credentials
    literals:
      - ADMIN_KEY=changeme

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: base
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cap
    app.kubernetes.io/version: 2.2.1

images:
  - name: "tiago2/cap"
    newTag: "2.2.1"
