---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - login-ingress.yaml
  - sa.yaml
  - pdb.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: base
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: cap
      app.kubernetes.io/version: 3.1.5

images:
  - name: swr.eu-de.otc.t-systems.com/opentelekomcloud/cap
    newTag: "3.1.5"
