- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  failed_when: false
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version == '22'

- name: Configure apt retries
  copy:
    mode: 0444
    src: 80retry
    dest: /etc/apt/apt.conf.d/80retry

- name: Disable apt translations
  copy:
    mode: 0444
    src: 90no-translations
    dest: /etc/apt/apt.conf.d/90no-translations

- name: Make /etc/apt/sources.list.d
  ansible.builtin.file:
    state: "directory"
    path: "/etc/apt/sources.list.d"

- name: Replace sources.list file
  copy:
    src: 'sources.list.{{ ansible_facts.lsb.codename }}.{{ ansible_facts.architecture }}'
    dest: "/etc/apt/sources.list.d/{{ ansible_facts.lsb.codename }}.list"
  notify: Update apt cache
