apiVersion: v2
name: prometheus-blackbox-exporter
description: Prometheus Blackbox Exporter for endpoint probing
version: 0.1.0
dependencies:
  - name: prometheus-blackbox-exporter
    version: "9.2.0"
    repository: "https://prometheus-community.github.io/helm-charts"
