apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cap

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: "preprod"
      app.kubernetes.io/managed-by: "argocd"
      environment: "preprod"

resources:
  - ../../base
  - namespace.yaml
  - ../../components/valkey/deployment.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: cap-config
    literals:
      - SERVER_PORT=3000
      - SERVER_HOSTNAME=0.0.0.0
      - REDIS_URL=redis://valkey:6379
      - DEMO_MODE=false
      - SHOW_ERRORS=false
      - DISABLE_ERROR_LOGGING=false

secretGenerator:
  - name: cap-credentials
    literals:
      - ADMIN_KEY=<path:secret/data/cap/server#admin-key>

images:
  - name: tiago2/cap
    newTag: "2.2.1"
