apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-storage-claim
  labels:
    app.kubernetes.io/component: postgres
spec:
  storageClassName: csi-disk-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
