---
apiVersion: v1
kind: Secret
metadata:
  name: apimon-executor-secret
  labels:
    app.kubernetes.io/name: apimon
    app.kubernetes.io/component: executor
type: Opaque
stringData:
  apimon-executor-secure.yaml: |
    alerta:
      token: CHANGE_ME_ALERTA_TOKEN
    executor:
      db_url: CHANGE_ME_DB_URL
