---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apimon-executor-config
  labels:
    app.kubernetes.io/name: apimon
    app.kubernetes.io/component: executor
data:
  apimon-executor.yaml: |
    secure: /etc/apimon_secure/apimon-executor-secure.yaml
    gear:
      - host: apimon-gearman
        port: 4730
    log:
      config: /etc/apimon/logging.conf
    alerta:
      endpoint: http://alerta:80
    executor:
      work_dir: /var/lib/apimon
      socket: /tmp/executor.socket
      zone: production_eu-de
      logs_cloud: swift
      load_multiplier: 2
    metrics:
      statsd:
        host: statsd
        port: 8125
  logging.conf: |
    [loggers]
    keys=root,apimon,gear

    [handlers]
    keys=console

    [formatters]
    keys=simple

    [logger_root]
    level=INFO
    handlers=console

    [logger_apimon]
    level=DEBUG
    handlers=console
    qualname=apimon
    propagate=0

    [logger_gear]
    level=WARNING
    handlers=console
    qualname=gear
    propagate=0

    [handler_console]
    level=DEBUG
    class=StreamHandler
    formatter=simple
    args=(sys.stdout,)

    [formatter_simple]
    format=%(asctime)s %(levelname)s %(name)s: %(message)s
    datefmt=

    [formatter_task]
    format=%(asctime)s %(name)s: %(message)s
