---
apiVersion: v1
kind: Secret
metadata:
  name: apimon-scheduler-secret
  labels:
    app.kubernetes.io/name: apimon
    app.kubernetes.io/component: scheduler
type: Opaque
stringData:
  scheduler-secure.yaml: |
    alerta:
      token: CHANGE_ME_ALERTA_TOKEN
    clouds: []
  apimon-epmon-secure.yaml: |
    alerta:
      token: CHANGE_ME_ALERTA_TOKEN
    clouds: []
