---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-disk-topology
  resources:
    requests:
      storage: 10Gi
