container_runtime: "/usr/bin/{{ container_command }}"
gitea_os_group: git
gitea_os_user: git

gitea_version: "1.26.2"
gitea_checksum: "sha256:5b37937b625de69196748f7293eee1a7363f8637ae6e3da3c359bb380bd61a6a"

arch_translation:
  amd64: amd64
  x86_64: amd64
  i386: 386

gitea_mailer_enable: false
