container_runtime: "/usr/bin/{{ container_command }}"
gitea_os_group: git
gitea_os_user: git

gitea_version: "1.26.0"
gitea_checksum: "sha256:49677a16cd5ee35f71a0d147a68d0af734d8e92f77028739192553d1588c2d09"

arch_translation:
  amd64: amd64
  x86_64: amd64
  i386: 386

gitea_mailer_enable: false
