container_runtime: "/usr/bin/{{ container_command }}"
gitea_os_group: git
gitea_os_user: git

gitea_version: "1.27.2"
gitea_checksum: "sha256:aa4e624ca6aa58a824a75562caecc2d206fcab8c70bc8fab765b456f182844fd"

arch_translation:
  amd64: amd64
  x86_64: amd64
  i386: 386

gitea_mailer_enable: false
