apiVersion: v1
kind: Secret
metadata:
  name: otc-ca-cert
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
type: Opaque
stringData:
  otc-ca.crt: |
    {{- .Values.otcCaCert | nindent 4 }}
