---
- project:
    default-branch: main
    check:
      jobs:
        - otc-tox-linters
    gate:
      jobs:
        - otc-tox-linters
    deploy:
      jobs:
        - infra-prod-base: &infra-prod-base

        - infra-prod-base-ext: &infra-prod-base-ext
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-grafana-dashboards: &infra-prod-grafana-dashboards
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-grafana-datasources: &infra-prod-grafana-datasources
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-keycloak: &infra-prod-service-keycloak
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-configure-keycloak: &infra-prod-configure-keycloak
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-install-cce: &infra-prod-install-cce
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-install-loadbalancer: &infra-prod-install-loadbalancer
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-opensearch: &infra-prod-service-opensearch
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-install-helm-chart: &infra-prod-install-helm-chart
            dependencies:
              - name: infra-prod-base
                soft: true
        - infra-prod-service-acme-ssl: &infra-prod-service-acme-ssl
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-alerta: &infra-prod-service-alerta
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-apimon-epmon: &infra-prod-service-apimon-epmon
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-apimon-executor: &infra-prod-service-apimon-executor
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-apimon-k8s: &infra-prod-service-apimon-k8s
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-apimon-scheduler: &infra-prod-service-apimon-scheduler
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-cloudmon: &infra-prod-service-cloudmon
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-gitea: &infra-prod-service-gitea
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-grafana: &infra-prod-service-grafana
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-graphite: &infra-prod-service-graphite
            dependencies:
              - name: infra-prod-base
                soft: true
              - name: infra-prod-service-memcached
                soft: true

        - infra-prod-service-swift-proxy: &infra-prod-service-swift-proxy
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-memcached: &infra-prod-service-memcached
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-octavia-proxy: &infra-prod-service-octavia-proxy
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-statsd: &infra-prod-service-statsd
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-proxy: &infra-prod-service-proxy
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-vault: &infra-prod-service-vault
            dependencies:
              - name: infra-prod-base
                soft: true

        - infra-prod-service-zookeeper: &infra-prod-service-zookeeper
            dependencies:
              - name: infra-prod-base
                soft: true

    periodic:
      # Nightly execution
      jobs:
        - infra-prod-base: *infra-prod-base
        - infra-prod-base-ext: *infra-prod-base-ext

        - infra-prod-install-loadbalancer: *infra-prod-install-loadbalancer
        - infra-prod-install-cce: *infra-prod-install-cce
        - infra-prod-service-opensearch: *infra-prod-service-opensearch
        - infra-prod-install-helm-chart: *infra-prod-install-helm-chart

        - infra-prod-grafana-dashboards: *infra-prod-grafana-dashboards
        - infra-prod-grafana-datasources: *infra-prod-grafana-datasources

        - infra-prod-service-keycloak: *infra-prod-service-keycloak
        - infra-prod-configure-keycloak: *infra-prod-configure-keycloak

        - infra-prod-service-acme-ssl: *infra-prod-service-acme-ssl
        - infra-prod-service-alerta: *infra-prod-service-alerta
        - infra-prod-service-apimon-epmon: *infra-prod-service-apimon-epmon
        - infra-prod-service-apimon-executor: *infra-prod-service-apimon-executor
        - infra-prod-service-apimon-k8s: *infra-prod-service-apimon-k8s
        - infra-prod-service-apimon-scheduler: *infra-prod-service-apimon-scheduler
        - infra-prod-service-gitea: *infra-prod-service-gitea
        - infra-prod-service-grafana: *infra-prod-service-grafana
        - infra-prod-service-graphite: *infra-prod-service-graphite
        - infra-prod-service-memcached: *infra-prod-service-memcached
        - infra-prod-service-statsd: *infra-prod-service-statsd
        - infra-prod-service-proxy: *infra-prod-service-proxy
        - infra-prod-service-vault: *infra-prod-service-vault
        - infra-prod-service-zookeeper: *infra-prod-service-zookeeper
        - infra-prod-service-swift-proxy: *infra-prod-service-swift-proxy

