{{- range .Values.instances }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccountName }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .name | quote }}
    {{- include "grafana.commonLabels" $ | nindent 4 }}
{{- end }}
