apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: valkey
    newName: "artifactory.devops.telekom.de/docker.io/library/valkey"
    newTag: "8.0-alpine"

resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml
  - configmap.yaml
