apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-valkey-storage-claim
  labels:
    app.kubernetes.io/component: valkey
spec:
  storageClassName: csi-disk-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
