---
# PVC for Zuul scheduler keys persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zuul-scheduler-keys
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/component: "zuul-scheduler"
spec:
  storageClassName: "csi-sfsturbo"
  volumeName: zuul-prod-scheduler-keys-sfs-turbo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
