{{- if and .Values.swrSecret .Values.swrSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.swrSecret.name | default "swr-secret" }}
  namespace: {{ .Values.swrSecret.namespace | default "argocd" }}
  annotations:
    replicator.v1.mittwald.de/replicate-to: ".*"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.swrSecret.registry | default "swr.eu-de.otc.t-systems.com" }}": {
          "auth": "<path:secret/data/swr/swr#swr_auth_base64>"
        }
      }
    }
{{- end }}
