tempo:
  tempo:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 20m
        memory: 256Mi
    retention: 72h
    multitenancyEnabled: false
    reportingEnabled: false
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    metricsGenerator:
      enabled: true
      remoteWriteUrl: http://kube-prometheus-stack-prep-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
  persistence:
    enabled: true
    storageClassName: csi-disk-retain
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  service:
    type: ClusterIP
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: kube-prometheus-stack-preprod
