---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-merger
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "opentelemetry/otel-instrumentation"
