apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm
namePrefix: hy3-

resources:
  - ../../base

patches:
  - path: patch-service.yaml
  - path: patch-service-headless.yaml
  - path: patch-statefulset.yaml